# Generated by Django 3.0.7 on 2020-06-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='description_rus',
            field=models.CharField(max_length=400),
        ),
    ]
